### PR TITLE
Update Cartfile.resolved

### PR DESCRIPTION
**Pull request by beached**
Updated to current master

### CODE REVIEW

**Comment by ps2** [comment]
I'm getting this error with bootstrap:

```
$ carthage bootstrap
The dependency graph contained a cycle:
Crypto: CommonCrypto
```

**Comment by ps2** [comment]
Looks like travis is getting the same error.  I'm on carthage 0.18

**Comment by loudnate** [comment]
I'm working on a fix.

**Comment by ps2** [comment]
This seems to be working for me: https://github.com/ps2/rileylink_ios/pull/234

**Pull request closed without merging**
