### PR TITLE
Radio tuning for WW pumps.

### PR DESCRIPTION
**Pull request by ps2**
This adds PumpRegion to MinimedKit, region dependent tuning and radio configuration to RileyLinkKit, and configuration of that setting to the RileyLink app.

### CODE REVIEW

**Comment by ps2** [comment]
Thanks @oskarpearson for some of the initial work on this, and tracking settings that work better with WW pumps: https://github.com/oskarpearson/mmeowlink/wiki/Non-USA-pump-settings

**Comment by loudnate** [comment]
LGTM; sometimes settings are necessary. 😉

**Comment by ps2** [comment]
I _did_ look for a way to auto-detect, but it's complicated with the different radio settings.

**Comment by loudnate** [comment]
For Loop I'd like to put this in the Pump ID screen.

**Pull request merged**
