### PR TITLE
Handling time change events during history UTC reconciliation

### PR DESCRIPTION
**Pull request by loudnate**
Before -> After

img_2520 img_2519

### CODE REVIEW

**Comment by ps2** [comment]
I firsthand experienced the issue with using local phone time zone as the timezone for pump events when we few out here on friday, so looking forward to all this history goodness you've been cooking up!

This change looks good, also. 👍

**Comment by loudnate** [comment]
Loop/MySentry Packers should have worked correctly with the time change, right?

**Comment by ps2** [comment]
Yeah, that was working.  It was the timestamp on events that were uploaded to NS.  So maybe that’s still an issue; I’ll need to check.

**Comment by loudnate** [comment]
I didn't change how MySentry packet timestamps were handled in the RL app. I haven't gone through and made sure that PumpState.timezone is being serialized to NSUserDefaults correctly there either, which would be a prerequisite.

**Pull request merged**
