### PR TITLE
{WIP} Worlwide pump support

### PR DESCRIPTION
**Pull request by oskarpearson**
Initial code to better support worldwide pumps. Unfortunately it's not quite working yet

Feedback welcome. One option discussed in Gitter chat is to auto-detect the frequency, then keep state. I think that is the right long term solution, but this seemed easier :)

### CODE REVIEW

**Comment by oskarpearson** [comment]
@loudnate You mentioned you wanted to comment. Beware - first ever swift code: I have no idea what I'm doing :)

**Comment by ps2** [comment]
Could you re-submit this against dev?

**Comment by loudnate** [comment]
I think direction-wise there's a few things we should do here. First, let's get the frequencies out of the mutable arrays on PumpState and into the Ops call.

Initially we can try both ranges, and if we need to optimize, store a "US/WW/Unknown" flag on PumpState once we have a match.

**Comment by oskarpearson** [comment]
Hi there.

I've been a little busy since the referendum - but hope to sort this out in the next few days. I'll refactor as soon as I get a moment.

Thanks for the suggestions - I think they make sense.

Oskar

**Pull request closed without merging**
